<a href="https://colab.research.google.com/github/mifm/examples/blob/master/WETB_fatigue.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#1 Install dependencies

In [0]:
%%capture
!pip install setuptools_scm future h5py pytest pytest-cov nose sphinx blosc pbr paramiko # pytables

In [0]:
%%capture
!pip install scipy pandas matplotlib cython xlrd coverage xlwt openpyxl psutil

#2 Install Wind Energy Toolbox

In [33]:
!pip install wetb

#3 Import the fatigue module

In [0]:
import numpy as np
import matplotlib.pyplot as plt
from wetb.fatigue_tools.fatigue import eq_load, cycle_matrix
from wetb.fatigue_tools.rainflowcounting import rainflowcount
rainflow_windap = rainflowcount.rainflow_windap
rainflow_astm = rainflowcount.rainflow_astm

#4 Inspect the Damage Equivalent Load routine, eq_load

In [0]:
?eq_load

#5 Run an example with your signal

In [36]:
signal1 = np.array([-2.0, 0.0, 1.0, 0.0, -3.0, 0.0, 5.0, 0.0, -1.0, 0.0, 3.0, 0.0, -4.0, 0.0, 4.0, 0.0, -2.0])
signal2 = signal1 * 1.1

# equivalent load for default wohler slopes
print (eq_load(signal1, no_bins=50, neq=17, rainflow_func=rainflow_windap))
print (eq_load(signal1, no_bins=50, neq=17, rainflow_func=rainflow_astm))

# Cycle matrix with 4 amplitude bins and 4 mean value bins
print (cycle_matrix(signal1, 4, 4, rainflow_func=rainflow_windap))
print (cycle_matrix(signal1, 4, 4, rainflow_func=rainflow_astm))

# Cycle matrix where signal1 and signal2 contributes with 50% each
print (cycle_matrix([(.5, signal1), (.5, signal2)], 4, 8, rainflow_func=rainflow_astm))


[[4.024613313976801, 4.745357541147315, 5.68897815218057, 6.276100306634951, 6.675634924670693, 6.96605474581875]]
[[4.007339465999502, 4.721598967469384, 5.657945376160993, 6.243278863166493, 6.643912250400255, 6.936829789229306]]
(array([[0. , 0. , 0. , 0. ],
       [0.5, 0.5, 0. , 1. ],
       [0. , 0. , 0. , 0.5],
       [0. , 0.5, 0.5, 0.5]]), array([ nan, 3.66, 5.94, 8.4 ]), array([0.  , 2.25, 4.5 , 6.75, 9.  ]), array([  nan, -0.1 ,  1.04,  0.5 ]), array([-0.94 , -0.445,  0.05 ,  0.545,  1.04 ]))
(array([[0. , 0. , 0. , 0. ],
       [0.5, 0.5, 0. , 1. ],
       [0. , 0. , 0. , 0.5],
       [0. , 0. , 0.5, 1. ]]), array([       nan, 3.66666667, 6.        , 8.25      ]), array([0.  , 2.25, 4.5 , 6.75, 9.  ]), array([        nan, -0.16666667,  1.        ,  0.375     ]), array([-1. , -0.5,  0. ,  0.5,  1. ]))
(array([[0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0.5, 0. , 0.5, 0. , 0. , 0. , 0. , 1. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0.5],
       [0. , 0. , 0. , 0. , 